routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('auth/{provider}','Auth\LoginController@redirectToProvider')->name('social-reg');
Route::get('auth/{provider}/callback','Auth\LoginController@handleProviderCallback');


Route::middleware(['auth','verified','isset-wallet'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('wallets','WalletController');
    Route::resource('records','RecordController')->only('index','create','store');
});

app/Record.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Record extends Model
{
    protected $fillable = ['wallet_id', 'amount','type'];

    const RECORD_TYPES = ['Debit','Credit'];

    public function wallet(){
        return $this->belongsTo(Wallet::class);
    }
}

app/Http/Controllers/RecordController.php
<?php

namespace App\Http\Controllers;

use App\Record;
use App\RecordType;
use App\Wallet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class RecordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('record.record-list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('record.record-add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
           'wallet_id' => ['required:in:'.auth()->user()->wallets->implode('id', ', ')],
           'amount' => ['required'],
           'type' => ['required']
        ]);

        $wallet = Wallet::findOrFail($request->wallet_id);
        if (auth()->user()->is($wallet->user)) {
            if($validatedData['type'] == 0){
                if (auth()->user()->balance >= $request->amount) {
                    auth()->user()->balance -= $request->amount;
                    $wallet->balance += $request->amount;
                    auth()->user()->update();
                    $wallet->update();
                    Record::create($validatedData);
                }else{
                    return redirect()->back()->with('message', 'Insufficient funds.Not enough money on your account');
                }
            }elseif ($validatedData['type'] == 1){
                if ($wallet->balance >= $request->amount) {
                    $wallet->balance -= $request->amount;
                    auth()->user()->balance += $request->amount;
                    auth()->user()->update();
                    $wallet->update();
                    Record::create($validatedData);
                }else{
                    return redirect()->back()->with('message', 'Insufficient funds.Not enough money on your wallet');
                }
            }
        } else {
            return abort(403);
        }

        return redirect()->route('records.index')->with('message','Record created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/record/record-add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if (session('message'))
                <div class="alert alert-danger">
                    {{ session('message') }}
                </div>
            @endif
        </div>
        <div class="row justify-content-center">
            <form action="{{ route('records.store') }}" method="post" class="wallet-form">
                @csrf
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Wallet</label>
                    <select class="form-control" name="wallet_id" id="exampleFormControlSelect1">
                        <option selected>Choose...</option>
                        @foreach(auth()->user()->wallets as $wallet)
                            <option value="{{ $wallet->id }}">{{ $wallet->name }}</option>
                        @endforeach
                    </select>
                    @error('wallet_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Type</label>
                    <select class="form-control" name="type" id="exampleFormControlSelect1">
                        <option selected>Choose...</option>
                        @foreach(Record::RECORD_TYPES as $key => $value)
                            <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                    </select>
                    @error('type')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Amount</label>
                    <input type="number" name="amount" class="form-control" placeholder="Enter Balance">
                    @error('amount')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/record/record-list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if (session('message'))
                <div class="alert alert-success">
                    {{ session('message') }}
                </div>
            @endif
        </div>
        <div class="row justify-content-end p-3">
            <a href="{{ route('records.create') }}" class="btn btn-success">Add Record</a>
        </div>
        <div class="row justify-content-center p-3">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Wallet Name</th>
                    <th scope="col">Record Amount</th>
                    <th scope="col">Type</th>
                </tr>
                </thead>
                <tbody>
                @foreach(auth()->user()->records as $record)
                    <tr>
                        <th scope="row">{{ $record->id }}</th>
                        <td>{{ $record->wallet->name }}</td>
                        <td>{{ $record->amount }}</td>
                        <td>{{ Record::RECORD_TYPES[$record->type]}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection