routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('auth/{provider}','Auth\LoginController@redirectToProvider')->name('social-reg');
Route::get('auth/{provider}/callback','Auth\LoginController@handleProviderCallback');


Route::middleware(['auth','verified','isset-wallet'])->group(function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('wallets','WalletController');
    Route::resource('records','RecordController')->only('index','create','store');
});

app/Wallet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    protected $fillable = ['name','type','balance','user_id'];

    public function getType(){
        return $this->belongsTo(WalletType::class,'type');
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/WalletType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WalletType extends Model
{
    public function wallets(){
        return $this->hasMany(Wallet::class,'type','id');
    }
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use App\Wallet;
use App\WalletType;
use Illuminate\Http\Request;

class WalletController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('wallet.wallet-list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $walletTypes = WalletType::all();
        return view('wallet.wallet-add',compact('walletTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $walletTypes = WalletType::all();

        $validatedData = $request->validate([
            'name' => ['required', 'unique:wallets','max:255'],
            'type' => ['required','in:'.$walletTypes->implode('id', ', ')],
            'balance' => ['required'],
        ]);

        $data = new Wallet($validatedData);

        auth()->user()->wallets()->save($data);

        return redirect()->route('wallets.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $wallet = Wallet::findOrFail($id);
        $walletTypes = WalletType::all();
        return view('wallet.wallet-edit',compact('wallet','walletTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $wallet = Wallet::findOrFail($id);
        $walletTypes = WalletType::all();

        $validatedData = $request->validate([
            'name' => ['sometimes','required', 'unique:wallets,id,' . $id,'max:255'],
            'type' => ['required','in:'.$walletTypes->implode('id', ', ')],
            'balance' => ['required'],
        ]);

        if (auth()->user()->is($wallet->user)) {
            $wallet->update($validatedData);
        }

        return redirect()->route('wallets.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $wallet = Wallet::findOrFail($id);
        if (auth()->user()->is($wallet->user)) {
            $wallet->delete();
            return redirect()->route('wallets.index');
        }
        return back();
    }
}

resources/views/wallet/wallet-add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <form action="{{ route('wallets.store') }}" method="post" class="wallet-form">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Enter Name">
                    @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Wallet Type</label>
                    <select class="form-control" name="type" id="exampleFormControlSelect1">
                        <option selected>Choose...</option>
                        @foreach($walletTypes as $walletType)
                            <option value="{{ $walletType->id }}">{{ $walletType->name }}</option>
                        @endforeach
                    </select>
                    @error('type')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Balance</label>
                    <input type="number" name="balance" class="form-control" placeholder="Enter Balance">
                    @error('balance')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/wallet/wallet-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            {{ Session::get("message") }}
            <form action="{{ route('wallets.update',$wallet->id) }}" method="post" class="wallet-form">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Enter Name" value="{{ $wallet->name }}">
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Wallet Type</label>
                    <select class="form-control" name="type" id="exampleFormControlSelect1">
                        <option selected>Choose...</option>
                        @foreach($walletTypes as $walletType)
                            <option value="{{ $walletType->id }}" @if($wallet->type === $walletType->id) selected @endif>{{ $walletType->name }}</option>
                        @endforeach
                    </select>
                    @error('type')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Balance</label>
                    <input type="number" name="balance" class="form-control" placeholder="Enter Balance" value="{{ $wallet->balance }}">
                    @error('balance')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/wallet/wallet-list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-end p-3">
            <a href="{{ route('wallets.create') }}" class="btn btn-success">Add Wallet</a>
        </div>
        <div class="row justify-content-center p-3">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Type</th>
                        <th scope="col">Total Amount</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(auth()->user()->wallets as $wallet)
                        <tr>
                            <th scope="row">{{ $wallet->id }}</th>
                            <td>{{ $wallet->name }}</td>
                            <td>{{ $wallet->getType->name }}</td>
                            <td>{{ $wallet->balance }}</td>
                            <td><a href="{{ route('wallets.edit',$wallet->id) }}" class="btn btn-primary">Edit</a></td>
                            <td>
                                <form action="{{ route('wallets.destroy',$wallet->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
        </div>
    </div>
@endsection